### ISSUE TITLE
[Suggestion]: add an option where I can limit the times you can teleport in your death zone.

### ISSUE THREAD

**Issue by Mimikyu1337** [Fuzss/deathfinder#14]
### Mod Loader (Optional)

Fabric

### Minecraft Version(s) (Optional)

1.20.1

### Suggestion (Required)

It would be great for survivor mode, so that players don't have the option of returning to where they died without any penalty.

**Comment by Fuzss** [comment]
You can only return once in survival mode. Also returning is no longer possible after five minutes.
