### ISSUE TITLE
[1.16.5] Death Tracker items don't get removed when approaching death position.

### ISSUE THREAD

**Issue by Gbergz** [Fuzss/deathfinder#3]
Title^ 

**Minecraft**: 1.16.5
**Forge**: 36.1.31
**DeathFinder**: DeathFinder-v1.3-1.16.2

I also have the [Gravestone](https://www.curseforge.com/minecraft/mc-mods/gravestone-mod) mod installed if that messes with anything in particular.
**-** Gbergz

**Comment by Fuzss** [comment]
Hmm, no, that's just my fault. That feature is really broken, I'll have to think of a different implementation when I get back to this.

**Comment by Fuzss** [comment]
I've decided to just removed this as I don't think it's a very important feature.

Also death tracker items in general have been removed from this mod, only the death compass has been split into a new [Death Compass](https://www.curseforge.com/minecraft/mc-mods/death-compass-forge) mod.
