### ISSUE TITLE
[Crash]: On start up

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Fuzss/deathfinder#6]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.1.0

### Notes (Required)

1. Install mod
2. Launch Minecraft
3. Crashes

### Crash Report (Required)

https://pastebin.com/2X512aFy

**Comment by Fuzss** [comment]
https://www.curseforge.com/minecraft/mc-mods/cardinal-components
