### ISSUE TITLE
[Suggestion]: Relations Dependencies

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Fuzss/deathfinder#7]
### Suggestion (Required)

For 1.19.2 on curseforge under relations for Dependencies I think you should add Cardinal Components (https://www.curseforge.com/minecraft/mc-mods/cardinal-components) since this mod required it

**Comment by Fuzss** [comment]
The fabric version file itself is marked as requiring Cardinal Components, I do not have any control over what’s included in the relations tab.
